spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create
spring.datasource.hikari.maximum-pool-size=1
# DB connection
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=${TEST_DB}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
