spring.profiles.include=secret
spring.application.name=maribong
server.port=8090
# DB connection
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=${PROD_DB}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
prop.host-url="localhost:8090"