spring.profiles.include=secret
spring.application.name=maribong
server.port=8090
# DB connection
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=${PROD_DB}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
# image setting
image.url.host=kyugyut.iptime.org
image.url.port=8090
image.url.upload-path=src/main/uploads
image.url.query-path=img
image.url.profile-path=profile
image.url.post-image-path=postimg