spring.profiles.include=secret
spring.application.name=maribong
server.port=8090
# DB connection
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://192.168.0.19:3306/maribong
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}